spring.application.name=gym-management-system

server.port=8080


spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:gymManagementSystem
spring.datasource.username=xyz
spring.datasource.password=123

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

#spring.sql.init.mode=always
#
spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#
#spring.jpa.show-sql=true


ssl.store.id=your_pass
ssl.store.password=your_pass

stripe.secretKey=your_pass




#spring.servlet.multipart.enabled=true
#spring.servlet.multipart.max-file-size=50MB
#spring.servlet.multipart.max-request-size=100MB
#
#server.tomcat.max-swallow-size=-1
##server.tomcat.max-http-form-post-size=100MB
#server.tomcat.max-http-form-post-size=104857600

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

#server.tomcat.max-swallow-size=104857600
#server.tomcat.max-http-form-post-size=104857600

#org.gradle.configuration-cache=true
#org.gradle.configuration-cache.problems=warn
#org.gradle.configuration-cache.max-problems=5