spring.application.name=gym-management-system

# ===============================
# Server
# ===============================

server.port=${PORT:8080}


# ===============================
# Database - MySQL / Railway
# ===============================

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=Asia/Dhaka&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.defer-datasource-initialization=false
spring.sql.init.mode=never


# ===============================
# H2 Console
# ===============================

spring.h2.console.enabled=false


# ===============================
# SSLCommerz
# ===============================

ssl.store.id=${SSL_STORE_ID}
ssl.store.password=${SSL_STORE_PASSWORD}


# ===============================
# Stripe
# ===============================

stripe.secretKey=${STRIPE_SECRET_KEY}


# ===============================
# Mail
# ===============================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true





spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

